# Generated by Django 3.1.2 on 2020-10-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('job_type', models.CharField(max_length=200, null=True)),
                ('year_of_experiance', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('gender_type', models.CharField(max_length=200, null=True)),
                ('notice_period', models.IntegerField(blank=True, default=0, null=True)),
                ('expected_salary', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
