# Generated by Django 3.1.1 on 2020-10-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumes',
            name='status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
