# Generated by Django 3.1.1 on 2020-10-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201024_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
