# Generated by Django 3.1.1 on 2020-10-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_resumes_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumes',
            name='mobile',
        ),
    ]
